CREATE DATABASE ticket_project;

USE ticket_project;

CREATE TABLE t_cdsc_items_control (
  ITEM_ID INT NOT NULL AUTO_INCREMENT,
  ID_AIG INT NULL,
  ID_RTC INT NULL,
  ITEM_TYPE ENUM('PROBLEM','INCIDENT','CHANGE_REQUEST'),
  START_TIMESTAMP TIMESTAMP DEFAULT 0,
  END_TIMESTAMP TIMESTAMP DEFAULT 0,
  TOTAL_HOURS DECIMAL(10,2) NULL,
  PRIMARY KEY (ITEM_ID))
ENGINE = InnoDB;